# Generated by Django 6.0.2 on 2026-02-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('perfume', 'Eau de Parfum'), ('skincare', 'Soin Visage'), ('body', 'Corps')], default='perfume', max_length=50),
        ),
    ]
